import { mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { chromium } from "playwright-core";

const output = new URL("../artifacts/", import.meta.url);
const baseUrl = process.env.BROWSER_BASE_URL || "http://127.0.0.1:4173";
await mkdir(output, { recursive: true });
const browser = await chromium.launch({
  executablePath: "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe",
  headless: true
});
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
const page = await context.newPage();
const consoleErrors = [];
const pageErrors = [];
page.on("console", message => { if (message.type() === "error") consoleErrors.push(message.text()); });
page.on("pageerror", error => pageErrors.push(error.message));
await page.goto(baseUrl, { waitUntil: "networkidle" });
if (!(await page.locator("body").innerText()).trim()) throw new Error("页面为空白");
if (!await page.getByRole("heading", { name: /从一份材料/ }).isVisible()) throw new Error("公开首页未显示");
if (!await page.locator("#quota-badge").isVisible()) throw new Error("免费体验状态未显示");
if (await page.locator(".pretty-select").count() !== 4) throw new Error("工作台四个自定义下拉栏未渲染");
if (!await page.locator(".pretty-select:has(#level) .select-action", { hasText: "展开" }).isVisible()) throw new Error("下拉栏缺少醒目的展开提示");
await page.locator(".pretty-select:has(#level) .select-trigger").click();
await page.locator(".pretty-select:has(#level) .select-option", { hasText: "基础入门（A1）" }).click();
if (await page.locator("#level").inputValue() !== "基础入门（A1）") throw new Error("基础水平选项没有同步值");
await page.locator(".pretty-select:has(#level) .select-trigger").click();
await page.locator(".pretty-select:has(#level) .select-option", { hasText: "自定义学习水平" }).click();
if (!await page.locator("#custom-level-field").isVisible()) throw new Error("自定义水平输入框未显示");
await page.locator("#custom-level").fill("只认识最常见的 500 个词");
await page.locator(".pretty-select:has(#max-words) .select-trigger").click();
await page.locator(".pretty-select:has(#max-words) .select-option", { hasText: "20" }).click();
if (await page.locator("#max-words").inputValue() !== "20") throw new Error("最多提取下拉没有同步值");
await page.locator(".pretty-select:has(#expansion) .select-trigger").click();
await page.locator(".pretty-select:has(#expansion) .select-option", { hasText: "附带派生词与短语" }).click();
if (await page.locator("#expansion").inputValue() !== "full") throw new Error("词汇扩展选项没有同步值");
const ocrImage = await page.evaluate(() => {
  const canvas = document.createElement("canvas");
  canvas.width = 1600;
  canvas.height = 480;
  const context = canvas.getContext("2d");
  context.fillStyle = "white";
  context.fillRect(0, 0, canvas.width, canvas.height);
  context.fillStyle = "black";
  context.font = "700 76px Arial";
  context.fillText("Robust temporal representations", 70, 170);
  context.fillText("improve model generalization.", 70, 300);
  return canvas.toDataURL("image/png").split(",")[1];
});
await page.locator("#file-input").setInputFiles({ name: "reading-note.png", mimeType: "image/png", buffer: Buffer.from(ocrImage, "base64") });
if (!await page.locator("#image-preview").isVisible()) throw new Error("图片预览未显示");
await page.locator("#extract-file").click();
try {
  await page.locator("#file-result.success").waitFor({ state: "visible", timeout: 90000 });
} catch (error) {
  throw new Error(`本地 OCR 超时：${await page.locator("#file-result").textContent()}；浏览器错误：${[...consoleErrors, ...pageErrors].join(" | ") || "无"}`, { cause: error });
}
if (!/robust/i.test(await page.locator("#source-text").inputValue())) throw new Error("本地 OCR 未识别示例英文");
await page.screenshot({ path: fileURLToPath(new URL("online-image-ocr.png", output)), fullPage: true });
await page.locator("#quota-badge").click();
if (!await page.locator("#quota-panel").isVisible()) throw new Error("免费规则说明未展开");
if (!await page.locator("#quota-panel").getByText(/连续 7×24 小时内不限分析次数/).isVisible()) throw new Error("免费规则不完整");
await page.keyboard.press("Escape");
await page.getByRole("button", { name: "查看结果示例" }).click();
if (await page.locator(".word-entry").count() < 3) throw new Error("免登录示例未渲染");
if (!await page.locator(".word-expansion").first().isVisible()) throw new Error("派生词与短语扩展未显示");
await page.locator(".word-expansion").first().locator("summary").click();
if (!await page.locator(".word-expansion").first().getByText("robustness", { exact: true }).isVisible()) throw new Error("词族内容未展开");
if (!await page.locator("#result-status.success").isVisible()) throw new Error("结果成功状态未显示");
await page.locator("#token-help").click();
if (!await page.locator("#token-explainer").getByText(/只分析和审核生词不需要 Token/).isVisible()) throw new Error("Token 说明未展开");
for (const path of ["/guide/", "/privacy/", "/help/", "/connections/"]) {
  const child = await context.newPage();
  child.on("pageerror", error => pageErrors.push(`${path}: ${error.message}`));
  await child.goto(new URL(path, baseUrl).href, { waitUntil: "networkidle" });
  if (!(await child.locator("main").innerText()).trim()) throw new Error(`${path} 页面为空`);
  await child.close();
}
const connectionPage = await context.newPage();
await connectionPage.route("**/api/models", route => route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify({ ok: true, provider: "Google Gemini", models: [{ id: "gemini-3.7-flash", name: "Gemini 3.7 Flash" }, { id: "gemini-3.7-pro", name: "Gemini 3.7 Pro" }] }) }));
await connectionPage.route("**/api/test-ai", route => route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify({ ok: true, message: "Google Gemini · gemini-3.7-pro 连接成功" }) }));
await connectionPage.route("**/api/test-maimemo", route => route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify({ ok: true, message: "墨墨 Token 连接成功" }) }));
await connectionPage.goto(new URL("/connections/", baseUrl).href, { waitUntil: "networkidle" });
await connectionPage.locator("#provider-trigger").click();
if (await connectionPage.locator(".provider-option").count() !== 15) throw new Error("服务商数量不是 15 家");
await connectionPage.screenshot({ path: fileURLToPath(new URL("connections-providers.png", output)), fullPage: true });
await connectionPage.locator('[data-provider="gemini"]').click();
if (await connectionPage.locator("#provider-name").textContent() !== "Google Gemini") throw new Error("自定义服务商下拉选择失败");
if (await connectionPage.locator("#api-key-link").getAttribute("href") !== "https://aistudio.google.com/app/apikey") throw new Error("API Key 官方入口未随服务商切换");
if (await connectionPage.locator("#api-key-link").getAttribute("target") !== "_blank") throw new Error("API Key 官方入口没有在新标签页打开");
await connectionPage.locator("#api-key").fill("test-api-key");
await connectionPage.locator("#api-key").dispatchEvent("change");
await connectionPage.getByText(/已自动识别 2 个模型/).waitFor({ state: "visible" });
await connectionPage.locator("#model-trigger").click();
await connectionPage.locator("#model-search").fill("pro");
await connectionPage.screenshot({ path: fileURLToPath(new URL("connections-models.png", output)), fullPage: true });
await connectionPage.locator('[data-model="gemini-3.7-pro"]').click();
await connectionPage.locator("#test-ai").click();
await connectionPage.getByText("Google Gemini · gemini-3.7-pro 连接成功", { exact: true }).waitFor({ state: "visible" });
await connectionPage.locator("#memo-token").fill("test-memo-token");
await connectionPage.locator("#test-memo").click();
await connectionPage.getByText("墨墨 Token 连接成功", { exact: true }).waitFor({ state: "visible" });
const savedProvider = await connectionPage.evaluate(() => JSON.parse(localStorage.getItem("momo_ai_config") || "null")?.provider);
if (savedProvider !== "gemini") throw new Error("测试成功后未保存所选服务商");
await connectionPage.locator("#model-trigger").click();
await connectionPage.locator('[data-model="gemini-3.7-flash"]').click();
const switchedModel = await connectionPage.evaluate(() => JSON.parse(localStorage.getItem("momo_ai_config") || "null")?.model);
if (switchedModel !== "gemini-3.7-flash") throw new Error("切换模型后没有立即持久保存");
await connectionPage.reload({ waitUntil: "networkidle" });
await connectionPage.getByText(/已自动识别 2 个模型/).waitFor({ state: "visible" });
if (await connectionPage.locator("#model-name").textContent() !== "gemini-3.7-flash") throw new Error("重新打开页面后没有恢复所选模型");
const restoredKey = await connectionPage.locator("#api-key").inputValue();
if (restoredKey !== "test-api-key") throw new Error("重新打开页面后没有恢复 API Key");
if (await connectionPage.locator("#memo-token").inputValue() !== "test-memo-token") throw new Error("重新打开页面后没有恢复墨墨 Token");
const persistedHome = await context.newPage();
await persistedHome.goto(baseUrl, { waitUntil: "networkidle" });
await persistedHome.locator("#ai-mode").selectOption("own");
if (!await persistedHome.locator("#ai-mode-note").getByText(/Google Gemini · gemini-3.7-flash/).isVisible()) throw new Error("工作台没有读取持久化模型配置");
await persistedHome.close();
await connectionPage.locator("#remember-connections").uncheck();
const sessionOnly = await connectionPage.evaluate(() => ({ local: localStorage.getItem("momo_ai_config"), session: sessionStorage.getItem("momo_ai_config") }));
if (sessionOnly.local || !sessionOnly.session) throw new Error("关闭记住连接后没有迁移到当前标签页");
await connectionPage.locator("#remember-connections").check();
const persistentAgain = await connectionPage.evaluate(() => ({ local: localStorage.getItem("momo_ai_config"), session: sessionStorage.getItem("momo_ai_config") }));
if (!persistentAgain.local || persistentAgain.session) throw new Error("重新开启记住连接后没有迁移到持久存储");
await connectionPage.screenshot({ path: fileURLToPath(new URL("connections.png", output)), fullPage: true });
await connectionPage.close();
const manualPage = await context.newPage();
await manualPage.addInitScript(() => localStorage.clear());
await manualPage.route("**/api/models", route => route.fulfill({ status: 400, contentType: "application/json", body: JSON.stringify({ ok: false, error: "该服务商没有返回模型列表。" }) }));
await manualPage.goto(new URL("/connections/", baseUrl).href, { waitUntil: "networkidle" });
await manualPage.locator("#provider-trigger").click();
await manualPage.locator('[data-provider="glm"]').click();
await manualPage.locator("#api-key").fill("test-glm-key");
await manualPage.locator("#api-key").dispatchEvent("change");
await manualPage.getByText(/已切换为手填模式/).waitFor({ state: "visible" });
if (!await manualPage.locator("#manual-model-field").isVisible()) throw new Error("模型识别失败后未显示手填模型名称");
await manualPage.locator("#manual-model").fill("glm-custom-endpoint");
await manualPage.screenshot({ path: fileURLToPath(new URL("connections-manual-model.png", output)), fullPage: true });
await manualPage.close();
const mobileConnections = await context.newPage();
await mobileConnections.setViewportSize({ width: 390, height: 844 });
await mobileConnections.goto(new URL("/connections/", baseUrl).href, { waitUntil: "networkidle" });
await mobileConnections.locator("#provider-trigger").click();
if (!await mobileConnections.locator("#provider-menu").isVisible()) throw new Error("移动端服务商下拉未显示");
await mobileConnections.screenshot({ path: fileURLToPath(new URL("connections-mobile.png", output)), fullPage: true });
await mobileConnections.close();
const failurePage = await context.newPage();
await failurePage.goto(baseUrl, { waitUntil: "networkidle" });
await failurePage.getByRole("button", { name: "粘贴文本" }).click();
await failurePage.locator("#paste-text").fill("Too short.");
await failurePage.getByRole("button", { name: "从这份材料中提取生词" }).click();
await failurePage.locator("#result-status.error").waitFor({ state: "visible" });
if (!await failurePage.getByText("本次分析没有完成", { exact: true }).isVisible()) throw new Error("分析失败状态未显示");
await failurePage.close();
await page.screenshot({ path: fileURLToPath(new URL("online-home.png", output)), fullPage: true });

const mobile = await context.newPage();
await mobile.setViewportSize({ width: 390, height: 844 });
await mobile.goto(baseUrl, { waitUntil: "networkidle" });
if (!await mobile.getByRole("heading", { name: /从一份材料/ }).isVisible()) throw new Error("移动端首页未显示");
await mobile.locator("#quota-badge").click();
if (!await mobile.locator("#quota-panel").isVisible()) throw new Error("移动端免费规则未显示");
await mobile.screenshot({ path: fileURLToPath(new URL("online-mobile.png", output)), fullPage: true });
await browser.close();
if (consoleErrors.length || pageErrors.length) throw new Error(`浏览器错误：${[...consoleErrors, ...pageErrors].join(" | ")}`);
console.log("BROWSER_CHECK_OK");
