import { mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { chromium } from "playwright-core";
import { encodeWav } from "../public/audio-utils.js";

const output = new URL("../artifacts/", import.meta.url);
const baseUrl = process.env.BROWSER_BASE_URL || "http://127.0.0.1:4173";
await mkdir(output, { recursive: true });
const browser = await chromium.launch({
  executablePath: "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe",
  headless: true
});
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
const page = await context.newPage();
const consoleErrors = [];
const pageErrors = [];
page.on("console", message => { if (message.type() === "error") consoleErrors.push(message.text()); });
page.on("pageerror", error => pageErrors.push(error.message));
await page.goto(baseUrl, { waitUntil: "networkidle" });
if (!(await page.locator("body").innerText()).trim()) throw new Error("页面为空白");
if (!await page.getByRole("heading", { name: /从一份材料/ }).isVisible()) throw new Error("公开首页未显示");
if (!await page.locator("#quota-badge").isVisible()) throw new Error("免费体验状态未显示");
if (await page.locator(".pretty-select").count() !== 4) throw new Error("工作台四个自定义下拉栏未渲染");
if (!await page.locator(".pretty-select:has(#level) .select-action", { hasText: "展开" }).isVisible()) throw new Error("下拉栏缺少醒目的展开提示");
await page.locator(".pretty-select:has(#level) .select-trigger").click();
await page.locator(".pretty-select:has(#level) .select-option", { hasText: "基础入门（A1）" }).click();
if (await page.locator("#level").inputValue() !== "基础入门（A1）") throw new Error("基础水平选项没有同步值");
await page.locator(".pretty-select:has(#level) .select-trigger").click();
await page.locator(".pretty-select:has(#level) .select-option", { hasText: "自定义学习水平" }).click();
if (!await page.locator("#custom-level-field").isVisible()) throw new Error("自定义水平输入框未显示");
await page.locator("#custom-level").fill("只认识最常见的 500 个词");
await page.locator(".pretty-select:has(#max-words) .select-trigger").click();
await page.locator(".pretty-select:has(#max-words) .select-option", { hasText: "20" }).click();
if (await page.locator("#max-words").inputValue() !== "20") throw new Error("最多提取下拉没有同步值");
await page.locator(".pretty-select:has(#expansion) .select-trigger").click();
await page.locator(".pretty-select:has(#expansion) .select-option", { hasText: "附带派生词与短语" }).click();
if (await page.locator("#expansion").inputValue() !== "full") throw new Error("词汇扩展选项没有同步值");
const ocrImage = await page.evaluate(() => {
  const canvas = document.createElement("canvas");
  canvas.width = 1600;
  canvas.height = 480;
  const context = canvas.getContext("2d");
  context.fillStyle = "white";
  context.fillRect(0, 0, canvas.width, canvas.height);
  context.fillStyle = "black";
  context.font = "700 76px Arial";
  context.fillText("Robust temporal representations", 70, 170);
  context.fillText("improve model generalization.", 70, 300);
  return canvas.toDataURL("image/png").split(",")[1];
});
await page.locator("#file-input").setInputFiles({ name: "reading-note.png", mimeType: "image/png", buffer: Buffer.from(ocrImage, "base64") });
if (!await page.locator("#image-preview").isVisible()) throw new Error("图片预览未显示");
await page.locator("#extract-file").click();
try {
  await page.locator("#file-result.success").waitFor({ state: "visible", timeout: 90000 });
} catch (error) {
  throw new Error(`本地 OCR 超时：${await page.locator("#file-result").textContent()}；浏览器错误：${[...consoleErrors, ...pageErrors].join(" | ") || "无"}`, { cause: error });
}
if (!/robust/i.test(await page.locator("#source-text").inputValue())) throw new Error("本地 OCR 未识别示例英文");
await page.screenshot({ path: fileURLToPath(new URL("online-image-ocr.png", output)), fullPage: true });
await page.locator("#quota-badge").click();
if (!await page.locator("#quota-panel").isVisible()) throw new Error("免费规则说明未展开");
if (!await page.locator("#quota-panel").getByText(/连续 7×24 小时内不限分析次数/).isVisible()) throw new Error("免费规则不完整");
await page.keyboard.press("Escape");
await page.getByRole("button", { name: "查看结果示例" }).click();
if (await page.locator(".word-entry").count() < 3) throw new Error("免登录示例未渲染");
if (!await page.locator(".word-expansion").first().isVisible()) throw new Error("派生词与短语扩展未显示");
await page.locator(".word-expansion").first().locator("summary").click();
if (!await page.locator(".word-expansion").first().getByText("robustness", { exact: true }).isVisible()) throw new Error("词族内容未展开");
if (!await page.locator("#result-status.success").isVisible()) throw new Error("结果成功状态未显示");
await page.locator("#token-help").click();
if (!await page.locator("#token-explainer").getByText(/只分析和审核生词不需要 Token/).isVisible()) throw new Error("Token 说明未展开");
for (const path of ["/music/", "/subtitles/", "/guide/", "/privacy/", "/help/", "/connections/"]) {
  const child = await context.newPage();
  child.on("pageerror", error => pageErrors.push(`${path}: ${error.message}`));
  await child.goto(new URL(path, baseUrl).href, { waitUntil: "networkidle" });
  if (!(await child.locator("main").innerText()).trim()) throw new Error(`${path} 页面为空`);
  await child.close();
}
const musicPage = await context.newPage();
musicPage.on("pageerror", error => pageErrors.push(`/music/: ${error.message}`));
await musicPage.route("**/api/music-search*", route => route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify({ ok: true, source: "Apple iTunes Search", results: [{ id: "music-1", title: "Yellow", artist: "Coldplay", album: "Parachutes", artworkUrl: "", previewUrl: "", duration: 266000, explicit: false, storeUrl: "https://music.apple.com/us/album/yellow/1122782080?i=1122782283" }] }) }));
await musicPage.route("**/api/transcribe", route => route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify({ ok: true, text: "Look at the stars, look how they shine for you.", segments: [{ start: 0, end: 2.4, text: "Look at the stars, look how they shine for you.", noSpeech: 0 }] }) }));
await musicPage.goto(new URL("/music/", baseUrl).href, { waitUntil: "networkidle" });
if (!await musicPage.getByRole("heading", { name: /听见旋律/ }).isVisible()) throw new Error("音乐歌词页面未显示");
await musicPage.locator("#music-query").fill("Yellow Coldplay");
await musicPage.getByRole("button", { name: "搜索歌曲" }).click();
await musicPage.locator(".music-result").first().click();
if (await musicPage.locator("#track-title").inputValue() !== "Yellow") throw new Error("歌曲搜索结果没有填入歌曲名");
if (await musicPage.locator("#track-artist").inputValue() !== "Coldplay") throw new Error("歌曲搜索结果没有填入歌手");
const samples = new Float32Array(16000);
for (let index = 0; index < samples.length; index += 1) samples[index] = Math.sin(index / 14) * .15;
const wav = encodeWav(samples, 16000);
await musicPage.locator("#music-file").setInputFiles({ name: "yellow.wav", mimeType: "audio/wav", buffer: Buffer.from(wav) });
await musicPage.locator("#music-file-status.ok").waitFor({ state: "visible" });
if (!await musicPage.locator("#music-wave").isVisible()) throw new Error("本地音频波形未显示");
await musicPage.locator("#speech-key").fill("test-groq-key");
await musicPage.getByRole("button", { name: "开始识别英文歌词" }).click();
await musicPage.locator("#speech-status.ok").waitFor({ state: "visible" });
if (!/Look at the stars/.test(await musicPage.locator("#lyrics-output").inputValue())) throw new Error("音乐转写结果没有显示");
await musicPage.screenshot({ path: fileURLToPath(new URL("music-lyrics.png", output)), fullPage: true });
await musicPage.getByRole("button", { name: /带着歌词去筛词/ }).click();
await musicPage.waitForURL(url => url.pathname === "/");
if (await musicPage.locator("#level").inputValue() !== "英文歌曲与歌词") throw new Error("歌词没有切换到英文歌曲筛选标准");
if (await musicPage.locator("#expansion").inputValue() !== "phrases") throw new Error("歌词没有默认开启短语扩展");
if (!/Look at the stars/.test(await musicPage.locator("#paste-text").inputValue())) throw new Error("歌词没有带入工作台");
await musicPage.screenshot({ path: fileURLToPath(new URL("music-handoff.png", output)), fullPage: true });
await musicPage.close();
const subtitlePage = await context.newPage();
await subtitlePage.goto(new URL("/subtitles/", baseUrl).href, { waitUntil: "networkidle" });
if (!await subtitlePage.getByRole("heading", { name: /让每句台词/ }).isVisible()) throw new Error("美剧字幕页面未显示");
const subtitleUpload = Buffer.from("1\n00:00:01,000 --> 00:00:03,000\nMONICA: Could you give me a hand?\n你能帮我一下吗？\n", "utf8");
await subtitlePage.locator("#subtitle-file").setInputFiles({ name: "friends-s01e01.srt", mimeType: "application/x-subrip", buffer: subtitleUpload });
await subtitlePage.getByRole("button", { name: "整理英文字幕" }).click();
await subtitlePage.locator(".timeline-cue").first().waitFor({ state: "visible" });
if (!/Could you give me a hand\?/.test(await subtitlePage.locator("#subtitle-output").inputValue())) throw new Error("上传的 SRT 文件没有在浏览器中正确读取");
await subtitlePage.getByRole("button", { name: "载入示例" }).click();
await subtitlePage.locator(".timeline-cue").first().waitFor({ state: "visible" });
if (await subtitlePage.locator(".timeline-cue").count() !== 3) throw new Error("示例字幕没有正确合并并去重");
if (!/\[00:00:04\]/.test(await subtitlePage.locator("#subtitle-output").inputValue())) throw new Error("字幕开始时间没有保留");
if (/[\u3400-\u9fff]/.test(await subtitlePage.locator("#subtitle-output").inputValue())) throw new Error("双语字幕中的中文没有清除");
await subtitlePage.screenshot({ path: fileURLToPath(new URL("subtitles-timeline.png", output)), fullPage: true });
await subtitlePage.getByRole("button", { name: /带着字幕去筛词/ }).click();
await subtitlePage.waitForURL(url => url.pathname === "/");
if (await subtitlePage.locator("#level").inputValue() !== "美剧日常口语") throw new Error("字幕没有切换到美剧日常口语标准");
if (await subtitlePage.locator("#expansion").inputValue() !== "full") throw new Error("字幕没有默认开启词汇与短语扩展");
if (!/\[00:00:04\]/.test(await subtitlePage.locator("#paste-text").inputValue())) throw new Error("字幕没有带入工作台");
if (!/City Stories · S01E03/.test(await subtitlePage.locator("#title").inputValue())) throw new Error("剧集信息没有带入词本名称");
await subtitlePage.screenshot({ path: fileURLToPath(new URL("subtitles-handoff.png", output)), fullPage: true });
await subtitlePage.close();
const connectionPage = await context.newPage();
await connectionPage.route("**/api/models", route => route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify({ ok: true, provider: "Google Gemini", models: [{ id: "gemini-3.7-flash", name: "Gemini 3.7 Flash" }, { id: "gemini-3.7-pro", name: "Gemini 3.7 Pro" }] }) }));
await connectionPage.route("**/api/test-ai", route => route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify({ ok: true, message: "Google Gemini · gemini-3.7-pro 连接成功" }) }));
await connectionPage.route("**/api/test-maimemo", route => route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify({ ok: true, message: "墨墨 Token 连接成功" }) }));
await connectionPage.goto(new URL("/connections/", baseUrl).href, { waitUntil: "networkidle" });
await connectionPage.locator("#provider-trigger").click();
if (await connectionPage.locator(".provider-option").count() !== 15) throw new Error("服务商数量不是 15 家");
await connectionPage.screenshot({ path: fileURLToPath(new URL("connections-providers.png", output)), fullPage: true });
await connectionPage.locator('[data-provider="gemini"]').click();
if (await connectionPage.locator("#provider-name").textContent() !== "Google Gemini") throw new Error("自定义服务商下拉选择失败");
if (await connectionPage.locator("#api-key-link").getAttribute("href") !== "https://aistudio.google.com/app/apikey") throw new Error("API Key 官方入口未随服务商切换");
if (await connectionPage.locator("#api-key-link").getAttribute("target") !== "_blank") throw new Error("API Key 官方入口没有在新标签页打开");
await connectionPage.locator("#api-key").fill("test-api-key");
await connectionPage.locator("#api-key").dispatchEvent("change");
await connectionPage.getByText(/已自动识别 2 个模型/).waitFor({ state: "visible" });
await connectionPage.locator("#model-trigger").click();
await connectionPage.locator("#model-search").fill("pro");
await connectionPage.screenshot({ path: fileURLToPath(new URL("connections-models.png", output)), fullPage: true });
await connectionPage.locator('[data-model="gemini-3.7-pro"]').click();
await connectionPage.locator("#test-ai").click();
await connectionPage.getByText("Google Gemini · gemini-3.7-pro 连接成功", { exact: true }).waitFor({ state: "visible" });
await connectionPage.locator("#memo-token").fill("test-memo-token");
await connectionPage.locator("#test-memo").click();
await connectionPage.getByText("墨墨 Token 连接成功", { exact: true }).waitFor({ state: "visible" });
const savedProvider = await connectionPage.evaluate(() => JSON.parse(localStorage.getItem("momo_ai_config") || "null")?.provider);
if (savedProvider !== "gemini") throw new Error("测试成功后未保存所选服务商");
await connectionPage.locator("#model-trigger").click();
await connectionPage.locator('[data-model="gemini-3.7-flash"]').click();
const switchedModel = await connectionPage.evaluate(() => JSON.parse(localStorage.getItem("momo_ai_config") || "null")?.model);
if (switchedModel !== "gemini-3.7-flash") throw new Error("切换模型后没有立即持久保存");
await connectionPage.reload({ waitUntil: "networkidle" });
await connectionPage.getByText(/已自动识别 2 个模型/).waitFor({ state: "visible" });
if (await connectionPage.locator("#model-name").textContent() !== "gemini-3.7-flash") throw new Error("重新打开页面后没有恢复所选模型");
const restoredKey = await connectionPage.locator("#api-key").inputValue();
if (restoredKey !== "test-api-key") throw new Error("重新打开页面后没有恢复 API Key");
if (await connectionPage.locator("#memo-token").inputValue() !== "test-memo-token") throw new Error("重新打开页面后没有恢复墨墨 Token");
const persistedHome = await context.newPage();
await persistedHome.goto(baseUrl, { waitUntil: "networkidle" });
await persistedHome.locator("#ai-mode").selectOption("own");
if (!await persistedHome.locator("#ai-mode-note").getByText(/Google Gemini · gemini-3.7-flash/).isVisible()) throw new Error("工作台没有读取持久化模型配置");
await persistedHome.close();
await connectionPage.locator("#remember-connections").uncheck();
const sessionOnly = await connectionPage.evaluate(() => ({ local: localStorage.getItem("momo_ai_config"), session: sessionStorage.getItem("momo_ai_config") }));
if (sessionOnly.local || !sessionOnly.session) throw new Error("关闭记住连接后没有迁移到当前标签页");
await connectionPage.locator("#remember-connections").check();
const persistentAgain = await connectionPage.evaluate(() => ({ local: localStorage.getItem("momo_ai_config"), session: sessionStorage.getItem("momo_ai_config") }));
if (!persistentAgain.local || persistentAgain.session) throw new Error("重新开启记住连接后没有迁移到持久存储");
await connectionPage.screenshot({ path: fileURLToPath(new URL("connections.png", output)), fullPage: true });
await connectionPage.close();
const manualPage = await context.newPage();
await manualPage.addInitScript(() => localStorage.clear());
await manualPage.route("**/api/models", route => route.fulfill({ status: 400, contentType: "application/json", body: JSON.stringify({ ok: false, error: "该服务商没有返回模型列表。" }) }));
await manualPage.goto(new URL("/connections/", baseUrl).href, { waitUntil: "networkidle" });
await manualPage.locator("#provider-trigger").click();
await manualPage.locator('[data-provider="glm"]').click();
await manualPage.locator("#api-key").fill("test-glm-key");
await manualPage.locator("#api-key").dispatchEvent("change");
await manualPage.getByText(/已切换为手填模式/).waitFor({ state: "visible" });
if (!await manualPage.locator("#manual-model-field").isVisible()) throw new Error("模型识别失败后未显示手填模型名称");
await manualPage.locator("#manual-model").fill("glm-custom-endpoint");
await manualPage.screenshot({ path: fileURLToPath(new URL("connections-manual-model.png", output)), fullPage: true });
await manualPage.close();
const mobileConnections = await context.newPage();
await mobileConnections.setViewportSize({ width: 390, height: 844 });
await mobileConnections.goto(new URL("/connections/", baseUrl).href, { waitUntil: "networkidle" });
await mobileConnections.locator("#provider-trigger").click();
if (!await mobileConnections.locator("#provider-menu").isVisible()) throw new Error("移动端服务商下拉未显示");
await mobileConnections.screenshot({ path: fileURLToPath(new URL("connections-mobile.png", output)), fullPage: true });
await mobileConnections.close();
const failurePage = await context.newPage();
await failurePage.goto(baseUrl, { waitUntil: "networkidle" });
await failurePage.getByRole("button", { name: "粘贴文本" }).click();
await failurePage.locator("#paste-text").fill("Too short.");
await failurePage.getByRole("button", { name: "从这份材料中提取生词" }).click();
await failurePage.locator("#result-status.error").waitFor({ state: "visible" });
if (!await failurePage.getByText("本次分析没有完成", { exact: true }).isVisible()) throw new Error("分析失败状态未显示");
await failurePage.close();
await page.screenshot({ path: fileURLToPath(new URL("online-home.png", output)), fullPage: true });

const mobile = await context.newPage();
await mobile.setViewportSize({ width: 390, height: 844 });
await mobile.goto(baseUrl, { waitUntil: "networkidle" });
if (!await mobile.getByRole("heading", { name: /从一份材料/ }).isVisible()) throw new Error("移动端首页未显示");
await mobile.locator("#quota-badge").click();
if (!await mobile.locator("#quota-panel").isVisible()) throw new Error("移动端免费规则未显示");
await mobile.screenshot({ path: fileURLToPath(new URL("online-mobile.png", output)), fullPage: true });
const subtitleMobile = await context.newPage();
await subtitleMobile.setViewportSize({ width: 390, height: 844 });
await subtitleMobile.goto(new URL("/subtitles/", baseUrl).href, { waitUntil: "networkidle" });
await subtitleMobile.getByRole("button", { name: "载入示例" }).click();
if (!await subtitleMobile.locator(".timeline-cue").first().isVisible()) throw new Error("移动端字幕时间轴未显示");
if (!await subtitleMobile.getByRole("button", { name: /带着字幕去筛词/ }).isVisible()) throw new Error("移动端字幕交接按钮未显示");
await subtitleMobile.screenshot({ path: fileURLToPath(new URL("subtitles-mobile.png", output)), fullPage: true });
await subtitleMobile.close();
const musicMobile = await context.newPage();
await musicMobile.setViewportSize({ width: 390, height: 844 });
await musicMobile.goto(new URL("/music/", baseUrl).href, { waitUntil: "networkidle" });
if (!await musicMobile.getByRole("heading", { name: /听见旋律/ }).isVisible()) throw new Error("移动端音乐页面未显示");
if (!await musicMobile.locator("#music-query").isVisible()) throw new Error("移动端歌曲搜索未显示");
await musicMobile.screenshot({ path: fileURLToPath(new URL("music-mobile.png", output)), fullPage: true });
await musicMobile.close();
await browser.close();
if (consoleErrors.length || pageErrors.length) throw new Error(`浏览器错误：${[...consoleErrors, ...pageErrors].join(" | ")}`);
console.log("BROWSER_CHECK_OK");
